// <auto-generated />
using System;
using FinalProjectIT3045.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProjectIT3045.Migrations
{
    [DbContext(typeof(FinalProjectTeammatesContext))]
    [Migration("20260727232455_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProjectIT3045.Models.CollegeCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ProfessorFirst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfessorLast")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CollegeCourses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseName = "Contemporary Programming",
                            EndDate = new DateOnly(2026, 8, 8),
                            ProfessorFirst = "Dyllon",
                            ProfessorLast = "Dekok",
                            StartDate = new DateOnly(2026, 5, 11),
                            Subject = "IT"
                        },
                        new
                        {
                            Id = 2,
                            CourseName = "Applied Statistics for Human Services",
                            EndDate = new DateOnly(2026, 8, 8),
                            ProfessorFirst = "Samuel",
                            ProfessorLast = "Adabla",
                            StartDate = new DateOnly(2026, 5, 11),
                            Subject = "Math"
                        },
                        new
                        {
                            Id = 3,
                            CourseName = "Human Computer Interaction",
                            EndDate = new DateOnly(2026, 8, 8),
                            ProfessorFirst = "Theodore",
                            ProfessorLast = "Langdon",
                            StartDate = new DateOnly(2026, 5, 11),
                            Subject = "IT"
                        },
                        new
                        {
                            Id = 4,
                            CourseName = "Web Game Development",
                            EndDate = new DateOnly(2026, 8, 8),
                            ProfessorFirst = "Andrew",
                            ProfessorLast = "Lively",
                            StartDate = new DateOnly(2026, 5, 11),
                            Subject = "IT"
                        });
                });

            modelBuilder.Entity("FinalProjectIT3045.Models.FavoriteBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FavoriteBooks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "F. Scott Fitzgerald",
                            Genre = "Fiction",
                            PublicationDate = new DateTime(1925, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Harper Lee",
                            Genre = "Fiction",
                            PublicationDate = new DateTime(1960, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 3,
                            Author = "George Orwell",
                            Genre = "Dystopian",
                            PublicationDate = new DateTime(1948, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "1984"
                        });
                });

            modelBuilder.Entity("FinalProjectIT3045.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Breed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Breed = "Husky",
                            Name = "Jacob",
                            Species = "Dog"
                        },
                        new
                        {
                            Id = 2,
                            Breed = "Chihuahua",
                            Name = "Brandy",
                            Species = "Dog"
                        },
                        new
                        {
                            Id = 3,
                            Breed = "DSH",
                            DateOfBirth = new DateOnly(2023, 5, 20),
                            Name = "Dice",
                            Species = "cat"
                        });
                });

            modelBuilder.Entity("FinalProjectIT3045.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CollegeProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearInProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CollegeProgram = "Information Technology",
                            DateOfBirth = new DateTime(2003, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Kaylah",
                            LastName = "Hammond",
                            YearInProgram = "Senior"
                        },
                        new
                        {
                            Id = 2,
                            CollegeProgram = "Information Technology",
                            DateOfBirth = new DateTime(2006, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Zoe",
                            LastName = "Aspenns",
                            YearInProgram = "Sophomore"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
